# For example:
multiprocessing: False
path_pretrained_models: './pretrained_models'
dataset:
    data_path: 'data'
blip_v2_model_type: blip2-flan-t5-xxl  # Change to blip2-flan-t5-xl for smaller GPUs
blip_half_precision: False
# Add more changes here, following the same format as base_config.yaml